### ISSUE TITLE
access via ssh

### ISSUE THREAD

**Issue by Grant-Steinfeld** [IBM/python-ubi-openshift#1]
Hi @stevemar 

Please can you assist me to getting write access to this repo I created for my code pattern?
Do I need to add a public ssh key somewhere?

It's odd as I can push to https://github.com/IBM/TDD-NodeJS-Containers

Sorry if I'm missing something obvious?

Thanks a ton!

Grant

**Comment by stevemar** [comment]
@Grant-Steinfeld you should have push access to the repo already. It's likely an ssh key issue, give me a shout tomorrow and we can debug it over webex.

**Comment by Grant-Steinfeld** [comment]
Thanks again @stevemar - all is well :)
